//description of function
/*
 * msg_proc.c: implementation of the
 * remote procedure "printmessage"
 */
#include <stdio.h>
#include "msg.h"				/* msg.h generated by rpcgen */
 
int *
printmessage_1_svc(msg, req)
	char **msg;	
	struct svc_req *req;		/* details of call */
{
	static int result;			/* must be static! */
	FILE *f;
 	printf("***In the remote procedure call(svc)***\n");
	f = fopen("/home/kseniya/emc/examples/my_test/log.txt", "w");
	if (f == (FILE *)NULL) {
		printf("***Can't open file!***\n");
		result = 0;
		return (&result);
	}
	printf("***Print message in seconds: %s\n***", *msg);
	fputs("I'm open!\n", f);
	fprintf(f, "%s\n", *msg);
	printf("Your message was: %s\n", *msg );
	fprintf(f, "%s\n", "I'm closed!");
	fclose(f);
	result = 1;
	return (&result);
}